# Inter-observer variability

**Important**: these scores correspond to the review made after the response from AMIA 2021. 

In [1]:
import numpy as np
import pandas as pd
from sklearn.metrics import cohen_kappa_score, confusion_matrix

In [2]:
file_path = "../Valoraciones_Cardiologos_Interobserver_review_AMIA2021.xlsx"
# Sheets' name
sheet_1 = "Valoración_Pepi"
sheet_2 = "Valoración_Daniel"
# We consider 0=not valid for assessment
df_1 = pd.read_excel(file_path, sheet_name=sheet_1, skiprows=2, usecols="C:O", index_col=0).replace({0:np.nan})
df_2 = pd.read_excel(file_path, sheet_name=sheet_2, skiprows=2, usecols="C:O", index_col=0).replace({0:np.nan})

<ipython-input-2-325427304cb5>:6: FutureWarning: Your version of xlrd is 1.2.0. In xlrd >= 2.0, only the xls format is supported. As a result, the openpyxl engine will be used if it is installed and the engine argument is not specified. Install openpyxl instead.
  df_1 = pd.read_excel(file_path, sheet_name=sheet_1, skiprows=2, usecols="C:O", index_col=0).replace({0:np.nan})
<ipython-input-2-325427304cb5>:7: FutureWarning: Your version of xlrd is 1.2.0. In xlrd >= 2.0, only the xls format is supported. As a result, the openpyxl engine will be used if it is installed and the engine argument is not specified. Install openpyxl instead.
  df_2 = pd.read_excel(file_path, sheet_name=sheet_2, skiprows=2, usecols="C:O", index_col=0).replace({0:np.nan})


In [3]:
df_1

C1   C2   C3   C4   C5   C6   C7   C8   C9  C10  C11  C12
Pepi                                                            
P51   5.0  5.0  5.0  5.0  5.0  5.0  5.0  5.0  5.0  5.0  5.0  5.0
P52   5.0  5.0  4.5  5.0  5.0  5.0  5.0  5.0  5.0  5.0  5.0  5.0
P53   3.0  4.5  4.5  5.0  5.0  5.0  5.0  5.0  5.0  5.0  5.0  NaN
P54   4.5  5.0  5.0  5.0  5.0  5.0  5.0  5.0  5.0  5.0  5.0  NaN
P55   NaN  5.0  5.0  5.0  5.0  5.0  5.0  5.0  5.0  5.0  5.0  NaN
P56   4.5  5.0  5.0  5.0  5.0  5.0  5.0  5.0  5.0  5.0  NaN  NaN
P57   5.0  5.0  5.0  5.0  5.0  5.0  5.0  5.0  5.0  NaN  NaN  NaN
P58   5.0  4.5  5.0  5.0  5.0  5.0  5.0  NaN  NaN  NaN  NaN  NaN
P59   5.0  5.0  5.0  5.0  5.0  5.0  5.0  5.0  5.0  NaN  NaN  NaN
P60   4.5  5.0  5.0  5.0  5.0  5.0  5.0  5.0  5.0  NaN  NaN  NaN
P61   5.0  5.0  5.0  5.0  5.0  5.0  5.0  5.0  NaN  NaN  NaN  NaN
P62   4.5  5.0  5.0  5.0  5.0  5.0  5.0  5.0  NaN  NaN  NaN  NaN
P63   5.0  5.0  5.0  5.0  5.0  5.0  5.0  5.0  NaN  NaN  NaN  NaN
P64   5.0  5.0  5.0  5.0  5.0  5.0  5.0  5.0  4.5  NaN  NaN  NaN
P65   5.0  5.0  5.0  5.0  5.0  5.0  5.0  5.0  5.0  NaN  NaN  NaN
P66   5.0  5.0  5.0  5.0  5.0  5.0  5.0  5.0  NaN  NaN  NaN  NaN
P67   5.0  5.0  5.0  5.0  5.0  5.0  5.0  5.0  NaN  NaN  NaN  NaN
P68   5.0  5.0  5.0  5.0  5.0  5.0  5.0  NaN  NaN  NaN  NaN  NaN
P69   5.0  5.0  5.0  5.0  5.0  5.0  5.0  NaN  NaN  NaN  NaN  NaN
P70   4.5  4.5  5.0  5.0  5.0  5.0  5.0  5.0  NaN  NaN  NaN  NaN
P71   4.5  5.0  5.0  5.0  5.0  5.0  NaN  NaN  NaN  NaN  NaN  NaN
P72   5.0  5.0  5.0  5.0  5.0  5.0  NaN  NaN  NaN  NaN  NaN  NaN
P73   5.0  5.0  5.0  5.0  5.0  5.0  NaN  NaN  NaN  NaN  NaN  NaN
P74   5.0  5.0  5.0  5.0  5.0  5.0  5.0  5.0  NaN  NaN  NaN  NaN
P75   5.0  5.0  5.0  5.0  5.0  5.0  5.0  NaN  NaN  NaN  NaN  NaN

In [4]:
df_2

C1   C2   C3   C4   C5   C6   C7   C8   C9  C10  C11  C12
Daniel                                                            
P51     5.0  5.0  4.0  5.0  4.5  5.0  5.0  5.0  5.0  4.0  4.5  4.5
P52     5.0  5.0  4.0  5.0  5.0  5.0  5.0  5.0  5.0  5.0  5.0  5.0
P53     4.0  4.0  5.0  5.0  5.0  5.0  5.0  5.0  5.0  5.0  5.0  5.0
P54     5.0  5.0  4.0  5.0  5.0  5.0  5.0  5.0  5.0  5.0  4.0  NaN
P55     2.0  5.0  5.0  4.5  4.0  5.0  5.0  5.0  5.0  4.5  4.5  4.0
P56     4.0  4.0  4.5  5.0  5.0  5.0  4.0  4.0  3.5  4.0  NaN  NaN
P57     3.5  4.0  4.0  5.0  5.0  5.0  5.0  5.0  5.0  NaN  NaN  NaN
P58     5.0  5.0  5.0  5.0  5.0  5.0  3.5  NaN  NaN  NaN  NaN  NaN
P59     4.5  5.0  5.0  5.0  5.0  5.0  4.5  4.5  5.0  NaN  NaN  NaN
P60     4.5  5.0  5.0  4.0  5.0  4.5  5.0  5.0  5.0  NaN  NaN  NaN
P61     4.5  4.5  4.5  4.5  4.5  5.0  5.0  4.0  NaN  NaN  NaN  NaN
P62     4.0  4.0  3.5  3.5  4.5  5.0  5.0  4.5  NaN  NaN  NaN  NaN
P63     3.5  4.0  4.5  5.0  5.0  5.0  4.5  4.5  NaN  NaN  NaN  NaN
P64     5.0  5.0  4.0  5.0  5.0  4.0  4.5  4.0  5.0  NaN  NaN  NaN
P65     5.0  5.0  5.0  4.0  4.0  4.0  5.0  5.0  4.0  NaN  NaN  NaN
P66     5.0  5.0  5.0  5.0  5.0  4.0  5.0  5.0  NaN  NaN  NaN  NaN
P67     4.0  5.0  5.0  5.0  5.0  5.0  5.0  5.0  NaN  NaN  NaN  NaN
P68     5.0  5.0  4.0  5.0  4.0  4.0  4.5  NaN  NaN  NaN  NaN  NaN
P69     5.0  5.0  5.0  5.0  5.0  5.0  5.0  NaN  NaN  NaN  NaN  NaN
P70     5.0  5.0  4.0  5.0  5.0  4.0  5.0  5.0  NaN  NaN  NaN  NaN
P71     5.0  5.0  5.0  5.0  5.0  5.0  NaN  NaN  NaN  NaN  NaN  NaN
P72     5.0  4.5  4.0  4.0  3.5  5.0  NaN  NaN  NaN  NaN  NaN  NaN
P73     4.0  4.0  5.0  5.0  5.0  5.0  1.0  1.0  NaN  NaN  NaN  NaN
P74     5.0  5.0  5.0  5.0  5.0  5.0  4.0  5.0  NaN  NaN  NaN  NaN
P75     5.0  5.0  5.0  5.0  5.0  5.0  5.0  NaN  NaN  NaN  NaN  NaN

In [5]:
df_min = np.minimum(df_1, df_2)

In [36]:
df_min

C1   C2   C3   C4   C5   C6   C7   C8   C9  C10  C11  C12
P51  5.0  5.0  4.0  5.0  4.5  5.0  5.0  5.0  5.0  4.0  4.5  4.5
P52  5.0  5.0  4.0  5.0  5.0  5.0  5.0  5.0  5.0  5.0  5.0  5.0
P53  3.0  4.0  4.5  5.0  5.0  5.0  5.0  5.0  5.0  5.0  5.0  NaN
P54  4.5  5.0  4.0  5.0  5.0  5.0  5.0  5.0  5.0  5.0  4.0  NaN
P55  NaN  5.0  5.0  4.5  4.0  5.0  5.0  5.0  5.0  4.5  4.5  NaN
P56  4.0  4.0  4.5  5.0  5.0  5.0  4.0  4.0  3.5  4.0  NaN  NaN
P57  3.5  4.0  4.0  5.0  5.0  5.0  5.0  5.0  5.0  NaN  NaN  NaN
P58  5.0  4.5  5.0  5.0  5.0  5.0  3.5  NaN  NaN  NaN  NaN  NaN
P59  4.5  5.0  5.0  5.0  5.0  5.0  4.5  4.5  5.0  NaN  NaN  NaN
P60  4.5  5.0  5.0  4.0  5.0  4.5  5.0  5.0  5.0  NaN  NaN  NaN
P61  4.5  4.5  4.5  4.5  4.5  5.0  5.0  4.0  NaN  NaN  NaN  NaN
P62  4.0  4.0  3.5  3.5  4.5  5.0  5.0  4.5  NaN  NaN  NaN  NaN
P63  3.5  4.0  4.5  5.0  5.0  5.0  4.5  4.5  NaN  NaN  NaN  NaN
P64  5.0  5.0  4.0  5.0  5.0  4.0  4.5  4.0  4.5  NaN  NaN  NaN
P65  5.0  5.0  5.0  4.0  4.0  4.0  5.0  5.0  4.0  NaN  NaN  NaN
P66  5.0  5.0  5.0  5.0  5.0  4.0  5.0  5.0  NaN  NaN  NaN  NaN
P67  4.0  5.0  5.0  5.0  5.0  5.0  5.0  5.0  NaN  NaN  NaN  NaN
P68  5.0  5.0  4.0  5.0  4.0  4.0  4.5  NaN  NaN  NaN  NaN  NaN
P69  5.0  5.0  5.0  5.0  5.0  5.0  5.0  NaN  NaN  NaN  NaN  NaN
P70  4.5  4.5  4.0  5.0  5.0  4.0  5.0  5.0  NaN  NaN  NaN  NaN
P71  4.5  5.0  5.0  5.0  5.0  5.0  NaN  NaN  NaN  NaN  NaN  NaN
P72  5.0  4.5  4.0  4.0  3.5  5.0  NaN  NaN  NaN  NaN  NaN  NaN
P73  4.0  4.0  5.0  5.0  5.0  5.0  NaN  NaN  NaN  NaN  NaN  NaN
P74  5.0  5.0  5.0  5.0  5.0  5.0  4.0  5.0  NaN  NaN  NaN  NaN
P75  5.0  5.0  5.0  5.0  5.0  5.0  5.0  NaN  NaN  NaN  NaN  NaN

In [6]:
scores_1 = df_1.values#.flatten()
scores_2 = df_2.values#.flatten()
#mask = np.argwhere(np.logical_and(~np.isnan(scores_1), ~np.isnan(scores_2))) # Discard samples for which any of the annotations is null
#scores_1, scores_2 = scores_1[mask], scores_2[mask]

In [7]:
scores_1.shape

(25, 12)

In [8]:
scores_2.shape

(25, 12)

## Considering scores as continious values

Inspired in http://dx.doi.org/10.21037/cdt.2017.03.12

In [9]:
abs_diff = abs(scores_1-scores_2)
addition = scores_1+scores_2
rel_diff = abs_diff/(addition/2)
abs_diff

array([[0. , 0. , 1. , 0. , 0.5, 0. , 0. , 0. , 0. , 1. , 0.5, 0.5],
       [0. , 0. , 0.5, 0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. ],
       [1. , 0.5, 0.5, 0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. , nan],
       [0.5, 0. , 1. , 0. , 0. , 0. , 0. , 0. , 0. , 0. , 1. , nan],
       [nan, 0. , 0. , 0.5, 1. , 0. , 0. , 0. , 0. , 0.5, 0.5, nan],
       [0.5, 1. , 0.5, 0. , 0. , 0. , 1. , 1. , 1.5, 1. , nan, nan],
       [1.5, 1. , 1. , 0. , 0. , 0. , 0. , 0. , 0. , nan, nan, nan],
       [0. , 0.5, 0. , 0. , 0. , 0. , 1.5, nan, nan, nan, nan, nan],
       [0.5, 0. , 0. , 0. , 0. , 0. , 0.5, 0.5, 0. , nan, nan, nan],
       [0. , 0. , 0. , 1. , 0. , 0.5, 0. , 0. , 0. , nan, nan, nan],
       [0.5, 0.5, 0.5, 0.5, 0.5, 0. , 0. , 1. , nan, nan, nan, nan],
       [0.5, 1. , 1.5, 1.5, 0.5, 0. , 0. , 0.5, nan, nan, nan, nan],
       [1.5, 1. , 0.5, 0. , 0. , 0. , 0.5, 0.5, nan, nan, nan, nan],
       [0. , 0. , 1. , 0. , 0. , 1. , 0.5, 1. , 0.5, nan, nan, nan],
       [0. , 0. , 0. , 1. , 1. , 1

In [10]:
rel_diff

array([[0.        , 0.        , 0.22222222, 0.        , 0.10526316,
        0.        , 0.        , 0.        , 0.        , 0.22222222,
        0.10526316, 0.10526316],
       [0.        , 0.        , 0.11764706, 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        ],
       [0.28571429, 0.11764706, 0.10526316, 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        ,        nan],
       [0.10526316, 0.        , 0.22222222, 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.22222222,        nan],
       [       nan, 0.        , 0.        , 0.10526316, 0.22222222,
        0.        , 0.        , 0.        , 0.        , 0.10526316,
        0.10526316,        nan],
       [0.11764706, 0.22222222, 0.10526316, 0.        , 0.        ,
        0.        , 0.22222222, 0.22222222, 0.35294118, 0.22222222,
               nan,

In [11]:
np.nanmean(abs_diff)

0.29577464788732394

In [12]:
np.nanstd(abs_diff)

0.4380183565466456

In [13]:
np.nanmean(rel_diff)

0.06594180378683061

In [14]:
np.nanstd(rel_diff)

0.09941798863613918

## Considering scores as categorical values

In [15]:
scores_1 = scores_1.flatten()
scores_2 = scores_2.flatten()
mask = np.logical_and(~np.isnan(scores_1), ~np.isnan(scores_2))
scores_1, scores_2 = scores_1[mask], scores_2[mask]

In [16]:
# https://stackoverflow.com/questions/11528150/inter-rater-agreement-in-python-cohens-kappa
cohen_kappa_score(scores_1*2, scores_2*2)

0.01607774911512383

In [17]:
(scores_1*2==scores_2*2).sum()/(len(scores_1))

0.6384976525821596

## Weighted kappa

In [18]:
cohen_kappa_score(scores_1*2, scores_2*2, sample_weight=abs_diff.flatten()[mask])

-0.07118278118885368

## ICC

https://www.statology.org/intraclass-correlation-coefficient-python/

In [19]:
!pip install pingouin

     |████████████████████████████████| 205 kB 5.4 MB/s 
     |████████████████████████████████| 285 kB 6.2 MB/s 
     |████████████████████████████████| 9.4 MB 5.6 MB/s 
     |████████████████████████████████| 807 kB 13.4 MB/s 
     |████████████████████████████████| 231 kB 12.1 MB/s 
  Created wheel for pingouin: filename=pingouin-0.3.12-py3-none-any.whl size=204286 sha256=bd0542bcee033c42249787eba297f534d8346ba0a813abb60d0ec3e898f1aa1c
  Stored in directory: /root/.cache/pip/wheels/56/74/f2/a766175283c1c2479db49da5e259a7ffa418ed584d43f5c058
  Created wheel for littleutils: filename=littleutils-0.2.2-py3-none-any.whl size=7049 sha256=38647ddfdbcaaf1827804a0e4cb791d62ebfb9b20459b4375b9668dce1f4d76a
  Stored in directory: /root/.cache/pip/wheels/6a/33/c4/0ef84d7f5568c2823e3d63a6e08988852fb9e4bc822034870a
Successfully built pingouin littleutils
You should consider upgrading via the '/opt/conda/bin/python -m pip install --upgrade pip' command.


In [20]:
import pingouin as pg

In [21]:
df = pd.DataFrame({
    "slice": list(range(len(scores_1)))+list(range(len(scores_1))),
    "rater": ["A"]*len(scores_1)+["B"]*len(scores_2),
    "rating": list(scores_1)+list(scores_2)
})

In [22]:
df

slice rater  rating
0        0     A     5.0
1        1     A     5.0
2        2     A     5.0
3        3     A     5.0
4        4     A     5.0
..     ...   ...     ...
421    208     B     5.0
422    209     B     5.0
423    210     B     5.0
424    211     B     5.0
425    212     B     5.0

[426 rows x 3 columns]

In [23]:
icc = pg.intraclass_corr(data=df, targets='slice', raters='rater', ratings='rating')

In [24]:
icc.set_index('Type')

Description       ICC         F  df1  df2      pval  \
Type                                                                     
ICC1    Single raters absolute -0.050795  0.903322  212  213  0.770325   
ICC2      Single random raters  0.060934  1.167768  212  212  0.129827   
ICC3       Single fixed raters  0.077392  1.167768  212  212  0.129827   
ICC1k  Average raters absolute -0.107025  0.903322  212  213  0.770325   
ICC2k    Average random raters  0.114869  1.167768  212  212  0.129827   
ICC3k     Average fixed raters  0.143666  1.167768  212  212  0.129827   

               CI95%  
Type                  
ICC1   [-0.18, 0.08]  
ICC2   [-0.05, 0.17]  
ICC3   [-0.06, 0.21]  
ICC1k  [-0.45, 0.15]  
ICC2k    [-0.1, 0.3]  
ICC3k  [-0.12, 0.35]

## Comparing if scores are grater than or equal to 4

In [39]:
threshold = 3.5

In [40]:
len(scores_1)==len(scores_2)

True

In [41]:
len(scores_1)

213

In [42]:
mask_1 = scores_1>=threshold
mask_2 = scores_2>=threshold

In [43]:
mask_1

array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True, False,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,

In [44]:
(mask_1 & mask_2).mean()

0.9953051643192489

In [56]:
np.logical_not(mask_2).sum()

7

In [57]:
scores_2[np.logical_not(mask_2)]

array([3.5, 3.5, 3.5, 3.5, 3.5, 3.5, 3.5])

In [68]:
np.unique(scores_1, return_counts=True)

(array([3. , 4.5, 5. , nan, nan, nan, nan, nan, nan, nan, nan, nan, nan,
        nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan,
        nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan,
        nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan,
        nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan,
        nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan,
        nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan]),
 array([  1,  12, 200,   1,   1,   1,   1,   1,   1,   1,   1,   1,   1,
          1,   1,   1,   1,   1,   1,   1,   1,   1,   1,   1,   1,   1,
          1,   1,   1,   1,   1,   1,   1,   1,   1,   1,   1,   1,   1,
          1,   1,   1,   1,   1,   1,   1,   1,   1,   1,   1,   1,   1,
          1,   1,   1,   1,   1,   1,   1,   1,   1,   1,   1,   1,   1,
          1,   1,   1,   1,   1,   1,   1,   1,   1,   1,   1,   1,   1,
          1,   1,   1,   1,   1,   1,   1,   1,   1,  

In [69]:
np.unique(df_2.values.flatten(), return_counts=True)

(array([1. , 2. , 3.5, 4. , 4.5, 5. , nan, nan, nan, nan, nan, nan, nan,
        nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan,
        nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan,
        nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan,
        nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan,
        nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan,
        nan, nan, nan, nan, nan, nan, nan, nan, nan, nan]),
 array([  2,   1,   7,  40,  25, 143,   1,   1,   1,   1,   1,   1,   1,
          1,   1,   1,   1,   1,   1,   1,   1,   1,   1,   1,   1,   1,
          1,   1,   1,   1,   1,   1,   1,   1,   1,   1,   1,   1,   1,
          1,   1,   1,   1,   1,   1,   1,   1,   1,   1,   1,   1,   1,
          1,   1,   1,   1,   1,   1,   1,   1,   1,   1,   1,   1,   1,
          1,   1,   1,   1,   1,   1,   1,   1,   1,   1,   1,   1,   1,
          1,   1,   1,   1,   1,   1,   1,   1,   1,   1]))

In [67]:
np.unique(df_min.values.flatten(), return_counts=True)

(array([3. , 3.5, 4. , 4.5, 5. , nan, nan, nan, nan, nan, nan, nan, nan,
        nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan,
        nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan,
        nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan,
        nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan,
        nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan,
        nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan,
        nan]),
 array([  1,   7,  38,  32, 135,   1,   1,   1,   1,   1,   1,   1,   1,
          1,   1,   1,   1,   1,   1,   1,   1,   1,   1,   1,   1,   1,
          1,   1,   1,   1,   1,   1,   1,   1,   1,   1,   1,   1,   1,
          1,   1,   1,   1,   1,   1,   1,   1,   1,   1,   1,   1,   1,
          1,   1,   1,   1,   1,   1,   1,   1,   1,   1,   1,   1,   1,
          1,   1,   1,   1,   1,   1,   1,   1,   1,   1,   1,   1,   1,
          1,   1,   1,   1,   1,   1

In [ ]:
np.unique()